version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    hostname: postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: phxpay_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "15433:5432"
    volumes:
      - ./extras/postgres/scripts:/docker-entrypoint-initdb.d
      - ./extras/postgres/postgresql.conf:/etc/postgresql/postgresql.conf